import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import { Dancing_Script } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

export const dancing_script = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-script",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        {children}
        <NextTopLoader />
      </body>
    </html>
  );
};

export default RootLayout;
